# Generated by Django 5.2.1 on 2025-06-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answered_at',
            new_name='created_at',
        ),
    ]
